<?php

namespace CodeUnion;

class CodeUnion
{


	public function __construct()
	{
	}

	/**
	 * It generates styles and script tags depending on whether the vite is running in dev or prod mode.
	 * If there is a hotfile generated by dev mode then dev files are loaded,
	 * otherwise the manifest file is checked to load production - built files.
	 */
	public function getStylesAndScripts(): void
	{
		$manifest_path = get_template_directory() . "/public/build/manifest.json";
		$manifest = wp_json_file_decode($manifest_path, ['associative' => true]);

		$hotfile_path = get_template_directory() . "/public/hotfile";

		$src_styles = get_template_directory_uri() . '/public/build/' . $manifest["src/scss/core.scss"]["file"];
		$src_scripts = get_template_directory_uri() . '/public/build/' . $manifest["src/js/Core.js"]["file"];

		$domain_host = strtolower($_SERVER['HTTP_HOST']);
		if (str_contains($domain_host, 'localhost')) {
			if (file_exists($hotfile_path)) {
				$src_styles = "http://localhost:5173/src/scss/core.scss";
				$src_scripts = "http://localhost:5173/src/js/Core.js";
				echo '<script type="module" src="http://localhost:5173/@vite/client"></script>';
			}
		}

		echo '<link rel="stylesheet" href="' . $src_styles . '" rel="preload" data-cookieconsent="ignore">';
		echo '<script type="module" src="' . $src_scripts . '" data-cookieconsent="ignore" defer></script>';
	}

	/**
	 * Generates HTML code for a heading along with class attribute and heading type HTML tag.
	 *
	 * @param string $tag_name HTML tag name.
	 * @param string $text Heading text.
	 * @param string $class CSS class name.
	 *
	 */
	public function getHeading(string $tag_name, string $text, string $class): void
	{
		echo '<' . $tag_name . ' class="' . $class . '">' . $text . '</' . $tag_name . '>';
	}

	/**
	 * Generates HTML code for a link along with class and target attribute based on the link field from ACF.
	 *
	 * @param array $link_arr ACF link array.
	 * @param string $class CSS class name.
	 *
	 */
	public function getLink(array $link_arr, string $class): void
	{
		$target = '';
		if ($link_arr['target']) $target = ' target="' . $link_arr['target'] . '"';
		$output = '<a href="' . $link_arr['url'] . '" class="' . $class . '"' . $target . '>' . $link_arr['title'] . '</a>';
		echo $output;
	}

	/**
	 * Generates css class names for section padding.
	 *
	 * @param string $pt Top padding size from list: small, medium, large.
	 * @param string $pb Bottom padding size from list: small, medium, large.
	 *
	 */
	public function getSpacingClasses(string $pt, string $pb): string
	{
		$map = [
				'small' => 'sm',
				'medium' => 'md',
				'large' => 'lg',
		];

		$ptClass = 'pt__' . ($map[$pt] ?? '');
		$pbClass = 'pb__' . ($map[$pb] ?? '');

		return "$ptClass $pbClass";
	}

	/**
	 * Generates css class name for blog section padding.
	 *
	 * @param string $pb Bottom padding size from list: small, medium, large.
	 *
	 */
	public function getBlogSpacingClasses(string $pb): string
	{
		$map = [
				'medium' => 'md',
				'large' => 'lg',
		];

		$pbClass = 'blogPb__' . ($map[$pb] ?? '');

		return "$pbClass";
	}

	/**
	 * Generates HTML code for a link along with class and target attribute based on the link field from ACF.
	 *
	 * @param array $link_arr ACF link array.
	 * @param string $class CSS class name.
	 * @param string $iconUrl Icon src path.
	 * @param string $iconAlt Alt for icon.
	 *
	 */
	public function getIconLink(array $link_arr, string $class, string $iconUrl, string $iconAlt): void
	{
		$target = '';
		if ($link_arr['target']) $target = ' target="' . $link_arr['target'] . '"';
		$output = '<a href="' . $link_arr['url'] . '" aria-label="' . $link_arr['title'] . '" class="' . $class . '"' . $target . '><span aria-hidden="true"><img src="' . $iconUrl . '" alt="' . $iconAlt . '" class="style-svg"></span></a>';
		echo $output;
	}

	public function getFavicons($color)
	{
		$link = get_template_directory_uri() . '/public/favicon';
		echo '
		<link rel="apple-touch-icon" sizes="57x57" href="' . $link . '/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="' . $link . '/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="' . $link . '/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="' . $link . '/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="' . $link . '/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="' . $link . '/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="' . $link . '/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="' . $link . '/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="' . $link . '/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="' . $link . '/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="' . $link . '/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="' . $link . '/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="' . $link . '/favicon-16x16.png">
		<link rel="manifest" href="' . $link . '/manifest.json">
		<meta name="msapplication-TileColor" content="' . $color . '">
		<meta name="msapplication-TileImage" content="' . $link . '/ms-icon-144x144.png">
		<meta name="theme-color" content="' . $color . '">
		';
	}

	/**
	 * Generates HTML code for a link (with icon) with class and target attribute based on the link field from ACF.
	 *
	 * @param array $link_arr ACF link array.
	 * @param string $class CSS class name.
	 * @param string $iconUrl Icon src path.
	 * @param string $iconAlt Alt for icon.
	 *
	 */
	public function getIconTextLink(array $link_arr, string $class, string $iconUrl, string $iconAlt): void
	{
		$target = '';
		if ($link_arr['target']) $target = ' target="' . $link_arr['target'] . '"';
		$output = '<a href="' . $link_arr['url'] . '" aria-label="' . $link_arr['title'] . '" class="' . $class . '"' . $target . '><span aria-hidden="true"><img src="' . $iconUrl . '" alt="' . $iconAlt . '" class="style-svg"></span><span class="' . $class . 'Text">' . $link_arr['title'] . '</span></a>';
		echo $output;
	}

	/**
	 * Generates HTML code for a breadcrumbs.
	 * Uses ACF repeater with link as item structure.
	 *
	 * @param array $breadcrumbs ACF Repeater with Link field structure.
	 *
	 */
	public function getBreadcrumbs(array $breadcrumbs): void
	{
		get_template_part("includes/components/breadcrumbs", null, ['breadcrumbs' => $breadcrumbs]);
	}
}
